name: backup

on:
  workflow_dispatch:
  schedule:
    - cron: '1 1 24 * *'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install github-backup==0.43.1
    - name: Update backups
      run: github-backup neovim --token ${{ secrets.PAT }} --incremental --issues --issue-comments --pulls --pull-comments
    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Backup update
        commit_user_name: Neovim Backup Bot
        commit_user_email: bot@neovim.io
        commit_author: neovim <bot@neovim.io>
